### ISSUE TITLE
Paragraph headings not recognised as sentences

### ISSUE THREAD

**Issue by feralvam** [neosyon/SimpTextAlign#1]
Hi,
When running the tool with default parameters, I get alignments such as these:

11:	**## Following In Some Generous Footsteps** In 2010 , Bill Gates and Warren Buffett publicly launched the Giving Pledge to encourage billionaires to donate the bulk of their wealth to charity .	---(0.8202991224743326)--->	9:	In 2010 , Bill Gates and Warren Buffett publicly launched the Giving Pledge to encourage billionaires to donate the bulk of their wealth to charity .

25:	**## Using Technology To Change Learning** In the open letter , Zuckerberg and Chan talked about the potential that technology offers to re-engineer the way children learn .	---(0.8480297902555115)--->	20:	In the open letter , Zuckerberg and Chan talked about the potential that technology offers to re-engineer the way children learn .

As can be seen, the section headings "## Following In Some Generous Footsteps" and "## Using Technology To Change Learning" were not correctly identified as sentences, despite being in a single line in the Newsela article. 

Is there a way to prevent this from happening? Maybe changing some property of the sentence splitter internally used by the tool? I haven't checked if this happens with every section heading in every article, but it does happen in all the ones I've manually checked (around 10 original articles with their 4 versions).

Thank you for your help,
Fernando

**Comment by neosyon** [comment]
Dear Fernando,

Thank you for pointing out this issue. We had a problem with the sentence splitter.

Now it's fixed. Let us know if you find any other issue.

Best

**Comment by sstajner** [comment]
Dear Fernando,

Another way to deal with the ## issue is to exclude lines that start with
## from the whole corpus before feeding it into our tool. We noticed that
those subtitles are usually either left unchanged or completely eliminated
in the simplified versions, so they do not really contribute to the TS
dataset built in this way.

Best regards,
Sanja

**Comment by feralvam** [comment]
@neosyon Thank you.

@sstajner Thanks for the advise. I think I will follow this approach because, as you've mentioned, those ## lines don't really add much information.
