### ISSUE TITLE
Where to change language???

### ISSUE THREAD

**Issue by Yusra995** [neosyon/SimpTextAlign#6]
If we want to apply this tool on other language.. Like I want to run this on the Urdu language 
then where to change OR mention language?

**Comment by neosyon** [comment]
Hi Yusra995. Please take a look to the readme file. The CNG strategy is language independent. I Recommend you that one. For the other two strategies you would need to train and connect your own embedding model. You can give the model name as argument to the ComputeSimilarityBetweenTexts jar.
